project:
  type: website
  output-dir: docs

website:
  bread-crumbs: false
  page-navigation: true
  draft-mode: unlinked
  
  open-graph: true
  
  sidebar:
    logo: "images/logo/logo_2.png"
    background: "#d6afa7"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/EleanaCab/scRNAseq-wshp/tree/main
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        icon: house
        contents:
          - href: workshop-overview.qmd
            text: Overview
          - href: workshop-team.qmd
            text: Team
          - href: workshop-prereqs.qmd
            text: Prerequisites
          - href: index.qmd
            text: Schedule
          - href: workshop-data.qmd
            text: Data Summary
      - section: "Pre-reading"
        icon: book
        contents:
          - href: pre-readings/day-2-pre-reading.qmd
            text: Day 2
          - href: pre-readings/day-3-pre-reading.qmd
            text: Day 3
      - section: "Daily materials"
        icon: pencil
        contents:
          - href: days-content/day-1.qmd
            text: "Day 1"
          - href: days-content/day-2.qmd
            text: "Day 2"
          - href: days-content/day-3.qmd
            text: "Day 3"
      - section: "Supplemental notes"
        icon: clipboard2-plus
        contents:
          - href: supplemental-material/additional-links.qmd
            text: Additional Resources
          - href: supplemental-material/install-packages.qmd
            text: Install Packages Script

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto


